version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd backend
      - npm ci
  build:
    commands:
      - zip -r ../backend.zip .
artifacts:
  files:
    - backend.zip
